ALTER TABLE customer ADD COLUMN street VARCHAR(255);
ALTER TABLE customer ADD COLUMN city VARCHAR(255);
ALTER TABLE customer ADD COLUMN state VARCHAR(255);
ALTER TABLE customer ADD COLUMN zip_code VARCHAR(20);
